### PR TITLE
feat(time): Turn on Chrono Furnaces

### LINKED ISSUE #80: Automatically turn on chrono furnace
### Describe the Feature

There should be an option to automatically turn on chrono furnaces, just like steamworks.

### Your Savegame

_No response_

### PR DESCRIPTION
**Pull request by oliversalzburg**
KS can now automatically turn on chrono furnaces, in case you forget.

Fixes #80

### CODE REVIEW

**Comment by oliversalzburg** [comment]
@petethered That is the intended behavior for this automation though. If you'd want to have this automation enabled/disabled, based on other factors, then that would be another feature on top of it or an alternative one (like "Build best unicorn building"). I don't like these kinds of features as they produce way too many branches in behavior.

In general, I'm not in favor of features that try to "play the game for you". Automations should be simple and predictable, especially when combined with each other. They may not be always ideal for fast progression, but they should be reasonable building blocks to automate specific stages of the game.

I know counter-examples of this exist in KS today, but those are mostly due to late contributions to v1.5 that were never in line with the original design of KS (as I perceive it).

Turning buildings on automatically is a feature already established by the steamworks. Similar features should behave consistent with this feature. So the related feature in any other tab should also be homed on the same tab as the building that is being turned on. Conditionally activating (and especially _deactivating_) isn't something that is really being used in KS so far, unless I'm forgetting something.

That being said, I could see adding a _trigger_ to these "turn on" features, but "turning off" is still a new concept. There might also be room for more complex automations in the future. If you want to open a dedicated issue for your improvement idea, we can come back to it in due time :)

**Comment by petethered** [comment]
> In general, I'm not in favor of features that try to "play the game for you". Automations should be simple and predictable, especially when combined with each other. They may not be always ideal for fast progression, but they should be reasonable building blocks to automate specific stages of the game.

This is a reasonable line of thinking.  Thanks for clarifying the goals (make it easier, not make it play for you).

On the other hand "unexpected synergy between options" leads to "why the fuck is this happening" from the users.  Admittedly, trying to figure out why things were/weren't happening got me digging through the source, but I'm the exception not the rule.

In this case:

[Kittens Game - Run 22 - Year 5350 - Spring, day 7.txt](https://github.com/kitten-science/kitten-scientists/files/10377912/Kittens.Game.-.Run.22.-.Year.5350.-.Spring.day.7.txt)

When you load that save, I'm in "Charon" , Time control is DISABLED for this cycle.

If you enable "Turn on Chrono Furnaces", I'm ripped OUT of the cycle via the furnaces.

image

If I'm a "general user", I'm confused as to why I'm skipping out of a cycle that I have disabled (to indicate I want to stay in it).

Especially given that the thing that did it is in a different part of the UI.

image

A simple , half step solution, that keeps to the spirit (don't auto play) but reduces confusion is to move "Turn on chrono furnaces" to time control below Tempus Fugit.  At least then, all the features that involve moving the clock automatically are in one place.

**Comment by oliversalzburg** [comment]
@petethered I agree that this is exactly the kind of situation that should be avoided and I also follow your reasoning for why "Time Control" is the better home for this feature due to it.

So it shall be moved, but I might rename it to set it apart from other "Turn on" options. Maybe "Burn Chrono Heat"?

We'll track this under:
- #113 

In general, users don't have the desired amount of control over time, especially when it comes to selecting a target time period to be in. When constructing a solution for this, the behavior of enabling Chrono Furnaces must be taken into account. It'll probably still take quite some time before a full iteration on this feature though.

**Comment by ptarjan** [comment]
+1 to doing something here. Can the "Time Skip" logic take into account how much stored heat you have and enable the automation on the Chrono Furnace, then turn off the automation to use fewer crystals? Semantically I would like to skip all the non-redmoon years and I can't see to encode that, since in its current state the system will skip using x45 crystals, build up 500% heat and then automatically skip over the exact season I wanted to be in.

**Pull request merged**
