### PR TITLE
feat(village): Add option to hold unprofitable festivals

### PR DESCRIPTION
**Pull request by acmihal**
The "Hold Festivals" option has some basic profitability conditions but does not consider cycle-based bonuses or kitten arrival speed bonuses. This PR adds an option to hold festivals even if they are not profitable by the existing criteria. Festivals must be held before hunting in the tick function because hunting will spend all remaining catpower, leaving none left to spend on festivals.

### CODE REVIEW

**Comment by oliversalzburg** [comment]
In general, I like this improvement. I don't like the idea so much of having overrides though. Do you think we could have something like this?

- [ ] Hold festivals if...
    - [ ] Catpower profitable
    - [ ] Culture profitable
    - [ ] Gold profitable
    - [ ] Cycle bonus applicable
    - [ ] Kitten arrival bonus applicable

Then maybe the user could configure the exact conditions under which a festival should be help. Let me know what you think.

**Comment by acmihal** [comment]
I feel like festivals are inexpensive enough that by the time you want to hold them automatically, they are essentially free and you no longer care about the profitability conditions anymore. My inclination was to remove them entirely, but I did not want to break the existing functionality just in case someone is using it.

**Comment by oliversalzburg** [comment]
After giving it more thought, it actually sounds like it could just be a case for a "limited" modifier on the setting. Default behavior would be _limited_, as it is right now, only holding profitable festivals. "unlimited" would be ignoring the profitability.

I know "limited" is not great in general, because it has so many different meanings throughout KS, but this might still be a good fit for the time being.

**Comment by oliversalzburg** [comment]
Closing due to unresolved discussions and diverged branches.

**Pull request closed without merging**
