### PR TITLE
Blackcoin buy/sell thresholds for #99

### PR DESCRIPTION
**Pull request by acmihal**
Implementation of UI elements and logic for setting the blackcoin trading buy/sell thresholds instead of using hardcoded thresholds. Needs testing: I noticed the game was no longer rendering the current blackcoin price on the trading tab and I'm not sure why that is.

### CODE REVIEW

**Comment by oliversalzburg** [comment]
I am wondering about the change in behavior. As I understand it, the previous approach would "wait for the best price", as in, it waits until we reach the bottom, before buying. With the new approach, the purchase is made right when the price falls below the threshold, when it will just continue to decline from thereon, which seems less ideal.

I like the simplification, but this aspect confuses me.

**Comment by acmihal** [comment]
I read over the game code as well as the KS code for blackcoin trading, and my conclusion is that the waitForBestPrice logic is both broken and unnecessary. There is no "continue to decline" pattern in the game code for blackcoin price adjustment. The price has a gradual increasing trend until it reaches 1100 and then there is an instantaneous crash, followed by a return to the gradual increasing trend. The hardcoded price of 860 to stop waitForBestPrice is too low to detect some crashes. It is possible for a crash to land as high as 880.22 and then the gradual increasing trend starts from there. So it is possible to miss one or more trading cycles waiting for a big-enough crash to happen. I don't think you would ever want to do this. Every cycle is profitable, so not trading while you wait for an especially big cycle seems wasteful.

The new code removes the waitForBestPrice condition and just uses a configurable buy threshold and sell threshold. Given that the price behavior is consistent increasing trend followed by an instantaneous crash, it is safe to continue buying right up until you sell just before the crash. The tick-to-tick price variance is very small so the thresholds can be close together. I made the defaults 1090 / 1095, but you could even do 1098 / 1099.

Usually you want the gap between buy and sell to be big enough that the system does not flicker between buy/sell as the tick-to-tick variance crosses the thresholds frequently in a short period of time. But since there are no trading fees I'm not sure this is actually harmful.

**Review by oliversalzburg — CHANGES_REQUESTED** [review]
Please change the commit message to include the kind and area of change and reference the issue in the body. Like so:
```
feat(trade): Blackcoin buy/sell thresholds

Closes #99
```
We need this for the changelog generation.

**Comment by oliversalzburg** [comment]
Merged in d1e10dba2893fa495757b004d22a219c9cdef17d

**Pull request closed without merging**
